#!/usr/bin/env bash

CURR_SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")

kube_repo=$(folderconfig get deployment_repo -default "kube-repo")
kube_repo="$CURR_SCRIPT_DIR/deploysit/$kube_repo"
yaml_path=$(folderconfig get yaml_path -default "environment-charts/sit/values.yaml")
number_of_chars=$(folderconfig get yaml_path -default "4")
git_commit=$(git log -n 1 --pretty=format:"%H" | cut "-c1-$number_of_chars")

full_yaml_path="$kube_repo/$yaml_path"

echo "Kube repo: $kube_repo"
echo "YAML repo: $yaml_path"
echo "Num of commit chars: $number_of_chars"
echo "Git commit: $git_commit"

cd "$kube_repo"
git pull
echo "modifying: $full_yaml_path"
cat $full_yaml_path



