#!/usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pushd "$parent_path" > /dev/null


if [ -z "$1" ]
  then
    cat "./data/profile.txt"
    echo
else
    printf "$1" > "./data/profile.txt"
fi



popd > /dev/null
