#!/usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pushd "$parent_path" > /dev/null
default_profile=$(cat "./data/profile.txt")
popd > /dev/null

awsudo -u "$default_profile" -- terraform apply "$@"



