#!/usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pushd "$parent_path" > /dev/null
default_profile=$(cat "./data/profile.txt")
popd > /dev/null

# Intern role, add this arguments: -refresh=false -lock=false 
if [[ "$default_profile" == Intern* ]] ;
then
    awsudo -u "$default_profile" -- terraform plan -refresh=false -lock=false -compact-warnings "$@"
else
    awsudo -u "$default_profile" -- terraform plan -compact-warnings "$@"
fi


