#!/usr/bin/env bash

CRED_FILE="vaultenv_creds"

# Check if the file exists
if [[ -f "$CRED_FILE" ]]; then
    echo "Exporting environment variables from $CRED_FILE"

    # Automatically export all variables when sourcing
    set -a
    source "$CRED_FILE"
    set +a

    echo "Environment variables exported successfully."
else
    echo "File '$CRED_FILE' does not exist. Please create it with export variable VAULT_TOKEN_PROD VAULT_TOKEN_SIT."
    exit 1
fi



if printf '%s\n' "$@" | grep -qx "prod"; then
  echo "Exporting prod environment..."
  export VAULT_ADDR="https://vault.automation.dana.id"
  export VAULT_TOKEN="$VAULT_TOKEN_PROD"
else
  echo "Exporting sit  environment..."
  export VAULT_ADDR="https://vault-sit.automation.dana.id"
  export VAULT_TOKEN="$VAULT_TOKEN_SIT"
fi